//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCHoppingliSt.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCHoppingliSt.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeváSCHárlóliSta.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új bolt nyitása.
        /// </summary>
        public static string CreateShopButton {
            get {
                return ResourceManager.GetString("CreateShopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az árukat nem, de a boltban tárolt pozícióikat elveszíted ezzel!.
        /// </summary>
        public static string DeleteShopAlertMessage {
            get {
                return ResourceManager.GetString("DeleteShopAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valóban törölni szeretnéd ezt a boltot?.
        /// </summary>
        public static string DeleteShopAlertQuestion {
            get {
                return ResourceManager.GetString("DeleteShopAlertQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolt törlése.
        /// </summary>
        public static string DeleteShopButton {
            get {
                return ResourceManager.GetString("DeleteShopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolt szerkesztése.
        /// </summary>
        public static string EditShopPageTitle {
            get {
                return ResourceManager.GetString("EditShopPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az ikon egyetlen karakter vagy emoji lehet.
        /// </summary>
        public static string IconTooLongError {
            get {
                return ResourceManager.GetString("IconTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Még nem nyitottál egy boltot sem..
        /// </summary>
        public static string MainPageEmptyText {
            get {
                return ResourceManager.GetString("MainPageEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolt mentése.
        /// </summary>
        public static string SaveShopButton {
            get {
                return ResourceManager.GetString("SaveShopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolt ikonja.
        /// </summary>
        public static string ShopIconLabel {
            get {
                return ResourceManager.GetString("ShopIconLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Válassz egy betűt vagy egy emojit.
        /// </summary>
        public static string ShopIconPlaceholder {
            get {
                return ResourceManager.GetString("ShopIconPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Már létezik ilyen nevű bolt!.
        /// </summary>
        public static string ShopNameAlreadyExistsAlertMessage {
            get {
                return ResourceManager.GetString("ShopNameAlreadyExistsAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felülírjuk a már létező boltot?.
        /// </summary>
        public static string ShopNameAlreadyExistsAlertQuestion {
            get {
                return ResourceManager.GetString("ShopNameAlreadyExistsAlertQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bolt neve nem lehet üres!.
        /// </summary>
        public static string ShopNameEmptyError {
            get {
                return ResourceManager.GetString("ShopNameEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolt neve.
        /// </summary>
        public static string ShopNameLabel {
            get {
                return ResourceManager.GetString("ShopNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itt nevezheted el az új boltot.
        /// </summary>
        public static string ShopNamePlaceholder {
            get {
                return ResourceManager.GetString("ShopNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kosarad még üres.
        /// </summary>
        public static string ShopPageItemsInBasketEmptyText {
            get {
                return ResourceManager.GetString("ShopPageItemsInBasketEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezeket már a kosaradba raktad.
        /// </summary>
        public static string ShopPageItemsInBasketHeaderText {
            get {
                return ResourceManager.GetString("ShopPageItemsInBasketHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs szükséged semmire sem innen.
        /// </summary>
        public static string ShopPageItemsOnListEmptyText {
            get {
                return ResourceManager.GetString("ShopPageItemsOnListEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeváSCHárlóliStád.
        /// </summary>
        public static string ShopPageItemsOnListHeaderText {
            get {
                return ResourceManager.GetString("ShopPageItemsOnListHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igen.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
