﻿global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using SCHoppingliSt.Model;
global using SCHoppingliSt.Resources;
global using SCHoppingliSt.Services;
global using SCHoppingliSt.View;
global using SCHoppingliSt.ViewModel;